name:                check-scheme
version:             0.0.1
github:              "czipperz/check-scheme"
license:             MIT
author:              "Chris Gregory"
maintainer:          "czipperz@gmail.com"
copyright:           "2019 Chris Gregory"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/czipperz/check-scheme#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- mtl

library:
  source-dirs: src

executables:
  check-scheme-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - check-scheme

tests:
  check-scheme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - check-scheme
    - HUnit
